### ISSUE TITLE
Unable to build from Master

### ISSUE THREAD

**Issue by prabhalar** [pedroigor/keycloak-authz#31]
Hi Pedro - A very interesting project. Would like to study and use it, if possible. 

Can you have a look and address the build issues that I am facing using the Master?

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.646 s
[INFO] Finished at: 2015-11-13T21:50:45-05:00
[INFO] Final Memory: 18M/79M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
1:compile (default-compile) on project keycloak-authz-persistence-api: Compilati
on failure: Compilation failure:
[ERROR] /C:/keycloak-authz-master/persistence/api/src/main/java/org/keycloak/aut
hz/persistence/syncronization/ClientApplicationSynchronizer.java:[11,78] cannot
find symbol
[ERROR] symbol:   class ClientRemovedEvent
[ERROR] location: interface org.keycloak.models.RealmModel
[ERROR] /C:/keycloak-authz-master/persistence/api/src/main/java/org/keycloak/aut
hz/persistence/syncronization/ClientApplicationSynchronizer.java:[14,39] cannot
find symbol

**Comment by pedroigor** [comment]
Hey @prabhalar, sorry for the late reply.

It seems you need to build my modified version of Keycloak first. Can you try this [1]. Or have you already tried that ?

[1] https://github.com/pedroigor/keycloak-authz#build

**Comment by prabhalar** [comment]
Ah - Missed that Pedro. Will try it shortly and let you know. 
Thanks,Raghu

**Comment by prabhalar** [comment]
Hi Pedro - A different issue now which I am trying to address by putting in a version 1.5 in a number of pom files (I know it is not the right way)

Thanks,
Raghu

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.239 s
[INFO] Finished at: 2015-12-19T15:43:44-05:00
[INFO] Final Memory: 24M/203M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project keycloak-authz-jpa-provider: Could not resolve dependencies for project org.keycloak:keycloak-authz-jpa-provider:jar:1.0-SNAPSHOT: Could not find artifact org.kohsuke.metainf-services:metainf-services:jar:1.5-jboss-1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :keycloak-authz-jpa-provider

**Comment by prabhalar** [comment]
The below change in keycloak-authz-parent/pom.xml fixed the issue.
<version.org.kohsuke.metainf-services.metainf-services>1.5</version.org.kohsuke.metainf-services.metainf-services>

But this is where I stopped

[INFO] Reactor Summary:
[INFO]
[INFO] Keycloak Authz: WildFly 9 Distribution Parent ...... SUCCESS [  0.448 s]
[INFO] Keycloak Authz: Wildfly 9 Authorization Server Feature Pack SUCCESS [ 11.597 s]
[INFO] Keycloak Authz: WildFly 9 Server Distribution ...... FAILURE [  1.522 s]
[INFO] Keycloak Authz: Wildfly 9 Adapter .................. SKIPPED
[INFO] Keycloak Authz: Wildfly 9 With AuthZ Adapters ...... SKIPPED
[INFO] Keycloak Authz: Distribution Parent ................ SKIPPED
[INFO] Keycloak Authz: Demo Distribution .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.023 s
[INFO] Finished at: 2015-12-19T16:56:42-05:00
[INFO] Final Memory: 62M/463M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.1.0.Final:build (server-provisioning) on project keycloak-authz-server-dist: Execution server-provisioning of goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.1.0.Final:build failed: java.lang.RuntimeException: java.lang.RuntimeException: failed to resolve artifact org.jboss.security:jboss-negotiation-common:jar:2.3.7.Final: Failure to find org.jboss.security:jboss-negotiation-common:jar:2.3.7.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.1.0.Final:build (server-provisioning) on project keycloak-authz-server-dist: Execution server-provisioning of goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.1.0.Final:build failed: java.lang.RuntimeException: java.lang.RuntimeException: failed to resolve artifact org.jboss.security:jboss-negotiation-common:jar:2.3.7.Final
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)

**Comment by pedroigor** [comment]
I've change kohsuke to 1.5.

Regarding your last error, can you try using this repository ?

    <repository>
            <id>jboss-public-repository-group</id>
            <name>JBoss Public Maven Repository Group</name>
            <url>http://repository.jboss.org/nexus/content/groups/public/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

**Comment by prabhalar** [comment]
Adding that to  keycloak-authz-modified pom.xml helped fix the problem and I was able to build. Thanks Pedro. Will test it out in the next few days and will let you know.
